"""Napari viewer for OME-Zarr OFF stacks.

This script loads OME-Zarr stacks generated by cnpix_local_sleep.stacks.write into napari
for visualization and annotation. The stacks include:
- AP: Grayscale rendered AP-band data (Group 0)
- Spikes: Binary spike presence overlay (Group 1)
- LFP: Rendered LFP traces overlay (Group 2)
- Structure borders: Structure boundary lines overlay (Group 3, if present)

All layers share the same pixel dimensions and can be overlaid directly.

Usage:
    python view_off_stacks_napari.py /path/to/off_stacks.ome.zarr

Example:
    python view_off_stacks_napari.py /data/CNPIX12/sam/Early.REC.NREM/off_stacks.ome.zarr
"""

import argparse
from pathlib import Path

import napari
import zarr


def load_ome_zarr_stacks(zarr_path: Path) -> dict[str, zarr.Array]:
    """Load OME-Zarr stacks from disk.

    Parameters
    ----------
    zarr_path
        Path to the OME-Zarr store.

    Returns
    -------
    dict[str, zarr.Array]
        Dictionary mapping layer names to zarr arrays.
    """
    root = zarr.open(str(zarr_path), mode="r")

    stacks = {}

    # Group 0: AP data
    if "0" in root:
        ap_group = root["0"]
        # OME-Zarr stores data in a "0" subgroup for the first resolution level
        if "0" in ap_group:
            stacks["ap"] = ap_group["0"]
        else:
            stacks["ap"] = ap_group

    # Group 1: Spikes
    if "1" in root:
        spike_group = root["1"]
        if "0" in spike_group:
            stacks["spikes"] = spike_group["0"]
        else:
            stacks["spikes"] = spike_group

    # Group 2: LFP
    if "2" in root:
        lf_group = root["2"]
        if "0" in lf_group:
            stacks["lf"] = lf_group["0"]
        else:
            stacks["lf"] = lf_group

    # Group 3: Structure borders (optional)
    if "3" in root:
        borders_group = root["3"]
        if "0" in borders_group:
            stacks["structure_borders"] = borders_group["0"]
        else:
            stacks["structure_borders"] = borders_group

    return stacks


def main():
    parser = argparse.ArgumentParser(
        description="View OME-Zarr OFF stacks in napari.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "zarr_path",
        type=str,
        help="Path to the OME-Zarr store (off_stacks.ome.zarr directory).",
    )

    args = parser.parse_args()

    zarr_path = Path(args.zarr_path)

    if not zarr_path.exists():
        raise FileNotFoundError(
            f"OME-Zarr store not found at {zarr_path}. "
            "Run cnpix_local_sleep.stacks.write.do_subject_probe first."
        )

    print(f"Loading OME-Zarr from: {zarr_path}")

    # Load stacks
    stacks = load_ome_zarr_stacks(zarr_path)

    # Create napari viewer
    viewer = napari.Viewer(title=f"OFF Stacks: {zarr_path.name}")

    # Scale factor for display: 2x height
    # For 3D stacks (t, y, x): scale is (t_scale, y_scale, x_scale)
    # For 2D images (y, x): scale is (y_scale, x_scale)
    scale_3d = (1, 2, 1)
    scale_2d = (2, 1)

    # Add AP layer as base image
    if "ap" in stacks:
        print(
            f"  Adding AP layer: shape={stacks['ap'].shape}, dtype={stacks['ap'].dtype}"
        )
        viewer.add_image(
            stacks["ap"],
            name="AP",
            colormap="viridis",
            blending="translucent",
            scale=scale_3d,
        )

    # Add spikes as overlay
    if "spikes" in stacks:
        print(
            f"  Adding spikes layer: shape={stacks['spikes'].shape}, "
            f"dtype={stacks['spikes'].dtype}"
        )
        viewer.add_image(
            stacks["spikes"],
            name="Spikes",
            colormap="gray",
            blending="additive",
            opacity=0.7,
            scale=scale_3d,
        )

    # Add LFP as overlay
    if "lf" in stacks:
        print(
            f"  Adding LFP layer: shape={stacks['lf'].shape}, "
            f"dtype={stacks['lf'].dtype}"
        )
        viewer.add_image(
            stacks["lf"],
            name="LFP",
            colormap="gray",
            blending="additive",
            opacity=0.5,
            scale=scale_3d,
        )

    # Add structure borders if present (binary uint8, same as LFP/spikes)
    if "structure_borders" in stacks:
        print(
            f"  Adding borders layer: shape={stacks['structure_borders'].shape}, "
            f"dtype={stacks['structure_borders'].dtype}"
        )
        viewer.add_image(
            stacks["structure_borders"],
            name="Structure Boundaries",
            colormap="red",
            blending="additive",
            opacity=0.8,
            scale=scale_2d,
        )

    print("\nnapari viewer launched. Use the slider to navigate through chunks.")
    print("Tip: Toggle layer visibility with the eye icon in the layers panel.")

    napari.run()


if __name__ == "__main__":
    main()
